# Generated by Django 4.2.3 on 2023-08-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField(verbose_name='Regno')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('standard', models.IntegerField(verbose_name='Standard')),
                ('marks', models.IntegerField(verbose_name='Marks')),
            ],
        ),
    ]
