# Generated by Django 4.2.3 on 2023-08-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Regno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.IntegerField(blank=True, null=True, verbose_name='Standard'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
    ]
