# Generated by Django 4.2.3 on 2023-08-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='EmpId')),
                ('empno', models.IntegerField(blank=True, null=True, verbose_name='EmpNo')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True, verbose_name='FirstName')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='LastName')),
                ('workdepartment', models.CharField(blank=True, max_length=100, null=True, verbose_name='WorkDepartment')),
                ('phoneno', models.IntegerField(blank=True, null=True, verbose_name='PhoneNo')),
                ('hiredate', models.DateField(blank=True, null=True, verbose_name='HireDate')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='BirthDate')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Salary')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bonus')),
            ],
        ),
    ]
