# Generated by Django 4.2.3 on 2023-08-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='software',
            fields=[
                ('Id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('Rating', models.FloatField(blank=True, null=True, verbose_name='Rating')),
                ('Company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('Jobtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jobtitle')),
                ('Salary', models.IntegerField(blank=True, null=True, verbose_name='Salary')),
                ('Salariesreported', models.IntegerField(blank=True, null=True, verbose_name='Salaryreported')),
                ('Location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('Employmentstatus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Employmentstatus')),
                ('Jobroles', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jobroles')),
            ],
        ),
    ]
